upstreams:
  init:
    # Configure startup behavior.
    # accepted: blocking, failOnError, fast
    # default: blocking
    strategy: fast
  groups:
    default:
      # Cloudflare
      - 1.1.1.1
      - 1.0.0.1
      # Quad9
      - 9.9.9.9
      - 149.112.112.112
      # Google
      - 8.8.8.8
      - 8.8.4.4
bootstrapDns:
  - tcp+udp:1.1.1.1
  - https://1.1.1.1/dns-query
  - tcp-tls:1.1.1.1:853 # Use DoT to connect to Cloudflare
  - 2606:4700:4700::1111 # And also do that via IPv6
  - upstream: https://dns.digitale-gesellschaft.ch/dns-query
    ips:
      - 185.95.218.42
blocking:
  denylists:
    ads:
      - https://adaway.org/hosts.txt
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      - https://big.oisd.nl/domainswild
      - https://v.firebog.net/hosts/AdguardDNS.txt
    tracking: # These hosts are used for tracking, which I want to avoid as hard as I can
      - https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt
      - https://v.firebog.net/hosts/Easyprivacy.txt
      - https://v.firebog.net/hosts/Prigent-Ads.txt
    malicious: # These are phising, malware & crypto mining sites
      - http://phishing.mailscanner.info/phishing.bad.sites.conf
      - https://v.firebog.net/hosts/Prigent-Crypto.txt
  clientGroupsBlock:
    default:
      - ads
      - tracking
      - malicious
ports:
  dns: 53
  http: 4000
prometheus:
  enable: true
  path: /metrics
