services:
  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - ./config:/www/assets # Make sure your local config directory exists
    ports:
      - 8080:8080
    user: 1000:1000 # default
    environment:
     - INIT_ASSETS=0 # default, requires the config directory to be writable for the container user (see user option)
    restart: unless-stopped
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.homer.rule=Host(`homer.local.patels.space`)"
     - "traefik.http.routers.homer.entrypoints=https"
     - "traefik.http.routers.homer.tls=true"
    networks:
     - proxy

networks:
  proxy:
    external: true
